#!/bin/sh
entries=$(dmenu_path 2>/dev/null)
declare -A arr
while IFS= read -r entry; do
    entry_basename="$(basename --suffix .desktop "$entry")"
    arr["$entry_basename"]="$entry"
done <<< "$entries"
basenames=$(for basename in "${!arr[@]}"; do echo "$basename"; done)
gio launch "${arr["$(echo "$basenames" | dmenu "$@" -l 9 -i)"]}"
