#!/bin/sh
directories=(
  "/usr/share/applications"
  "/usr/local/share/applications"
  "$HOME/.local/share/applications"
  "$HOME/Desktop"
)

find "${directories[@]}" -type f -iname "*.desktop" -print0 | \
  sort -z | \
  while IFS= read -r -d '' file; do
      echo "$file"
  done
